# Generated by Django 4.2.6 on 2023-10-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_image_shoe_additional_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
